language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
    - os: linux
      sudo: required
      python: 3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      eval "CC=gcc-6 && CXX=g++-6";
      fi

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install sphinx numpydoc sphinx_rtd_theme breathe;
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install doxygen; fi

script:
  - if [ "$TRAVIS_BRANCH" == "master" ] | [ "$TRAVIS_BRANCH" == "develop" ];
    then travis_wait 70 py.test -v -m travis;
    else travis_wait 30 py.test -v -m basic;
    fi

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] | [ "$TRAVIS_BRANCH" == "develop" ];
    if [ "$PYTHON" == "3.5" ] && [ "$OS" == "linux" ];
    then sh bin/update-documentation.sh;
    fi;
    fi

env:
  global:
   # GH_TOKEN BayAreaMetro/fast-trips public_repo token
  - secure: "ZhM0KwjxqZmGJndxXIoy+8qhbr+IVgGiyqc6itc1+YGlZonkrY0Fjodu+oZalUAtDzuG6gWOQwsPeV013p+867SkY0DsfyaCodjk5B//UQRjjBxFv+g/vxBYnpMrgD4nEqt7FutN7dQN/quWE+FlkfFuMlibmfi5ZFVMLbBaGv8="
