language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
      packages:
        - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      sudo: required
      python: 3.6
      packages:
        - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: osx
      sudo: required
      env:
        - pyv: 2.7
    - os: osx
      sudo: required
      env:
        - pyv: 3.6
  allow_failures:
    - os: osx

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      eval "${MATRIX_EVAL}";
      fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install pyenv
      pyenv install "${PYV}";
      fi

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install sphinx numpydoc sphinx_rtd_theme breathe;
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install doxygen; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew doxygen; fi

script:
  - if [ "$TRAVIS_BRANCH" == "master" ] | [ "$TRAVIS_BRANCH" == "develop" ];
    then travis_wait 70 py.test -v -m travis;
    else travis_wait 30 py.test -v -m basic;
    fi

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] | [ "$TRAVIS_BRANCH" == "develop" ];
    if [ "$PYTHON" == "3.5" ] && [ "$OS" == "linux" ];
    then sh bin/update-documentation.sh;
    fi;
    fi

env:
  global:
   # GH_TOKEN BayAreaMetro/fast-trips public_repo token
  - secure: "ZhM0KwjxqZmGJndxXIoy+8qhbr+IVgGiyqc6itc1+YGlZonkrY0Fjodu+oZalUAtDzuG6gWOQwsPeV013p+867SkY0DsfyaCodjk5B//UQRjjBxFv+g/vxBYnpMrgD4nEqt7FutN7dQN/quWE+FlkfFuMlibmfi5ZFVMLbBaGv8="
