language: python

python:
  - "2.7.13"
  - "3.7"

install:
  - sudo apt-get update
  - pip install -r requirements.txt
  - pip install .

script:
- if [ "$TRAVIS_BRANCH" == "master" ] | [ "$TRAVIS_BRANCH" == "develop" ];
  then travis_wait 70 py.test -v -m travis;
  else travis_wait 30 py.test -v -m basic;
  fi
